# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-17 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='Description', max_length=255),
        ),
    ]
