# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-18 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0003_auto_20180518_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uploaded_books',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to='app_name.Book'),
        ),
    ]
