# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-19 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0008_auto_20180518_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='liked_books',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uploaded_books',
        ),
        migrations.AddField(
            model_name='book',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_books', to='app_name.User'),
        ),
        migrations.AddField(
            model_name='book',
            name='uploader',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_books', to='app_name.User'),
            preserve_default=False,
        ),
    ]
